fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
print(fruits.count('apple'))
print(fruits.count('tangerine'))
print(fruits.index('banana'))
print(fruits.index('banana', 4))
print(fruits.reverse())
print(fruits.append('grape'))
print(fruits.sort())
print(fruits.pop())
print(fruits)